### ISSUE TITLE
#Offset does not yet do anyhting and needs to be implemented

### ISSUE THREAD

**Issue by Jerry-kiwi** [pysal/gwr#3]
Offset functionality for Poisson distibution is still dead?
It seems, that it is taken in account, but returning results are strange:
1. result of fit() funtion is in log scale
2. residuals are calculated as natural values of exog and log scale of fitted.

thanks for answer

**Comment by TaylorOshan** [comment]
Hi @Jerry-kiwi,

That is correct, the offset functionality has not yet been implemented. As a result, any unique diagnostics that are associated with including an offset also need to be implemented. This is definitely on the agenda and it is expected that these missing features will start being implemented in early 2018, along some additional advanced features that have been recently developed. PR's welcome towards this cause if you are interested in contributing and I am happy to review.

**Comment by Ziqi-Li** [comment]
@TaylorOshan @Jerry-kiwi 
Just tested the `spglm.iwls` against `statsmodel` with added `offset` argument and they agree with each other. One thing to note that there are two arguments in `statsmodels.genmod.generalized_linear_model.GLM`, one is `exposure` and the other is `offset`. They all do the same thing with one difference is that when using `exposure`, it will take the log-scale of it as the offset. To be clearer, 
`sm_model = sm.GLM(y, X,family=sm.families.Poisson(),offset=np.log(off.reshape(-1)))` will give same results as
`sm_model = sm.GLM(y, X,family=sm.families.Poisson(),exposure=off.reshape(-1))` 
See this [doc](http://www.statsmodels.org/dev/generated/statsmodels.genmod.generalized_linear_model.GLM.html) for details.

In GWR, for now, it seems like it treats `offset` as `exposure`, so there is no need to log it manually.

Also tested `pysal/gwr` with GWR4, and they also agree. 

See this [notebook](https://gist.github.com/Ziqi-Li/af391b40a780e70c2315b3c41a45be7e) for testing results.

@Jerry-kiwi if the strange results still happened, do you mind sharing with the data so that we could have a look?

**Comment by TaylorOshan** [comment]
Thanks for checking out the details @Ziqi-Li.

Indeed, it does actually seem that offset functionality is implemented...I must have done it a but ago and totally forgot about it! 

Going to close this for now, but happy feel free to reopen it @Jerry-kiwi  if you find things are still not working.
